# Generated by Django 3.0.5 on 2020-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='user_profile.Certification'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='education',
            field=models.ManyToManyField(blank=True, to='user_profile.Education'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='languages',
            field=models.ManyToManyField(blank=True, to='user_profile.Language'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='user_profile.Skill'),
        ),
    ]
