# Generated by Django 3.0.5 on 2020-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_myuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birth_date',
            field=models.DateField(blank=True, default=None, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True),
        ),
    ]
