# Generated by Django 3.0.5 on 2020-05-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200505_1436'),
        ('user_management', '0007_auto_20200504_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='languages',
            field=models.ManyToManyField(blank=True, to='user_profile.LanguageProficiency'),
        ),
    ]
