# Generated by Django 3.0.5 on 2020-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200507_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
