# Generated by Django 3.0.5 on 2020-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20200504_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
