# Generated by Django 3.0.5 on 2020-05-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_myuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
