# Generated by Django 3.0.5 on 2020-05-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20200504_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_photos'),
        ),
    ]
