# Generated by Django 3.0.5 on 2020-05-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20200506_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='college',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='education',
            name='country',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(default='', max_length=75),
        ),
    ]
