# Generated by Django 3.0.5 on 2020-05-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200508_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='deleted_but_visible_home',
            field=models.BooleanField(default=False),
        ),
    ]
