# Generated by Django 3.0.5 on 2020-05-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
