# Generated by Django 3.0.5 on 2020-05-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200511_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_offered', to='posts.Offer')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='which_offered', to='posts.Request')),
            ],
            options={
                'unique_together': {('offer', 'request')},
            },
        ),
    ]
