# Generated by Django 3.0.5 on 2020-05-12 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0013_offerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_who_bought', to='posts.Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
