# Generated by Django 3.0.5 on 2020-05-04 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('certifiedFrom', models.CharField(max_length=254)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1960), user_profile.models.max_value_current_year], verbose_name='year')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=254)),
                ('college', models.CharField(max_length=254)),
                ('major', models.CharField(max_length=254)),
                ('graduation_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1960), user_profile.models.max_value_current_year], verbose_name='year')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('levelInt', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['levelInt'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('levelInt', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['levelInt'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('experience_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='user_profile.ExperienceLevel')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='user_profile.LanguageLevel')),
            ],
        ),
    ]
