on:
  push:
    branches:
      - '*' 
  pull_request:
    branches: 
      - '**' 
  release:
    types: [published, edited]

jobs:
  build:
    name: Run code tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint the code
      #continue-on-error: true
      run: |
        pylint --fail-under=6 --load-plugins pylint_django --django-settings-module ProgettoArduAlessio.settings Base posts #intergrated_messaging user_management user_profile
        
    - name: Run Tests and Coverage
      run: |
        #python manage.py test
        coverage run --source='.' manage.py test
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
          tag_with_ref: true # Info: https://github.com/docker/build-push-action/tree/releases/v1#tag_with_ref
          tag_with_sha: true # Info: https://github.com/docker/build-push-action/tree/releases/v1#tag_with_sha
          tags: latest